# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "../Overseer/fastlane/Fastfile"

default_platform(:ios)

platform :ios do
  scheme_name = "Feige"
  module_name = "Feige"
  info_plist_path = "Feige/Info.plist"
  podspec_name = "Feige.podspec"
  xcodeproj_path = "Feige.xcodeproj"

  ENV[scheme_name.upcase] = scheme_name
  ENV[xcodeproj_path.upcase] = xcodeproj_path
  ENV[module_name.upcase] = module_name
  ENV[info_plist_path.upcase] = info_plist_path
  ENV[podspec_name.upcase] = podspec_name
end
