# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "../Overseer/fastlane/Fastfile"

default_platform(:ios)

platform :ios do
  scheme_name = "Feige"
  module_name = "Feige"
  info_plist_path = "Feige/Info.plist"
  podspec_name = "Feige.podspec"
  xcodeproj_path = "Feige.xcodeproj"
  plist_bundle_short_version_string_key = "CFBundleShortVersionString"

  desc "Unit tests"
  lane :unit_tests_feige do
    unit_tests(scheme: scheme_name)
  end

  desc "Generate code coverage file"
  lane :code_coverage_feige do
    code_coverage(scheme: scheme_name, xcodeproj_path: xcodeproj_path)
  end

  desc "Update docs"
  lane :update_docs_feige do
    update_docs(module: module_name, info_plist_path: info_plist_path)
  end

  desc "Create push git tag"
  lane :create_push_git_tag_feige do
    create_push_git_tag(info_plist_path: info_plist_path)
  end

  desc "Set short version string"
  lane :set_short_version_string do
    Dir.chdir("..") do
      short_version_string = prompt(text: "Short version string: ")

      sh("./scripts/set_info_plist_key.sh #{plist_bundle_short_version_string_key} #{short_version_string}")
      sh("./scripts/set_podspec_version.sh #{short_version_string}")
      sh("git commit -a -m \"Bump version to #{short_version_string}\"")
    end
  end
end
